# Module 0.2 - NumPy

_PAS4AI Workforce Summer 2024_

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/joonbugs/My-Test-Repository/blob/main/Large_Language_Models.ipynb)

# LLM Rules:
You may freely use the 'modules_llm' discord bot. You may not use any other LLM. 

This discord bot uses the same prompt as the function from Module 0, but has the ability to "remember" past responses.

You should explain the prompts that you used and how the responses helped you as comments in the respective answer cells. 
If you use the llm to find out what a function does, you should also search for that answer online and see if you can find it/understand the documentation - state this as a comment in your answer cell.

# What is NumPy?

NumPy is a Python library for **numerical computations**. It provides high-performance multidimensional array objects and functions for working with these arrays. NumPy is widely used in scientific computing and data analysis.

In Deep Learning, NumPy is used to represent and manipulate numerical data, such as **images or text**, as multidimensional arrays, which are then used as inputs to neural networks.

NumPy also provides efficient implementations of mathematical operations, such as matrix multiplication and convolution, which are the building blocks of many DL algorithms.

In [ ]:
import numpy as np

## NumPy 1D Arrays

A one-dimensional NumPy array is a data structure that represents a sequence of values of the same data type arranged in a single row. It can be created using the `numpy.array()` function, which takes a list or tuple of values as input.

One-dimensional arrays can be indexed and sliced like Python lists, and support vectorized operations, such as addition or multiplication by a scalar, element-wise addition or multiplication, and more.

One-dimensional arrays are commonly used to **represent time-series data, signal processing**, or as inputs to machine learning models.

In [ ]:
a = np.array([1,2,3])

## NumPy 2D Arrays

A two-dimensional NumPy array is a data structure that represents a table of values arranged in rows and columns. It can be created using the **numpy.array()** function with a list of lists as input, where each nested list represents a row of values.

Two-dimensional arrays can be indexed and sliced using row and column indices, and support various mathematical operations, such as matrix multiplication and element-wise addition or multiplication.

Two-dimensional arrays are commonly used to **represent images, tabular data**, or as inputs to machine learning models.

In [ ]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)

## NumPy 3D Arrays

A three-dimensional NumPy array is a data structure that represents a collection of 2D arrays arranged along a third axis. It can be created using the `numpy.array()` function with a list of 2D arrays as input, where each 2D array represents a slice along the third axis.

Three-dimensional arrays can be indexed and sliced using three indices that correspond to the three axes. They support various mathematical operations, such as element-wise addition or multiplication, matrix multiplication, and convolution.

Three-dimensional arrays are commonly used to **represent volumetric data** in medical imaging, computer graphics, or as inputs to 3D convolutional neural networks in deep learning.





In [ ]:
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)

# Placeholders

## ```np.zeros((a,b))```

In [ ]:
# Creates an array of zeros of the size a x b.
print(np.zeros((2, 3)))

## ```np.ones((a,b))```

In [ ]:
# Creates an array of ones of the size a x b.
print(np.ones((4, 5)))

##```np.arrange(a,b,c)```


In [ ]:
# Creates an array of evenly spaced values with gaps of c(step value) between a and b.
print(np.arange(10,25,2))

##```np.linspace(a,b,c)```

In [ ]:
# Creates an array of evenly spaced values with c samples between a and b.
print(np.linspace(10,25,4))

##```np.random.random((a,b))```


In [ ]:
# Creates an array with random values of the size of a x b.
print(np.random.random((2, 3)))

## ```np.empty((a,b))```

`empty`, unlike `zeros`, does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.

In [ ]:
# Create an empty array of the size a x b.
print(np.empty((4, 6)))

# Question 1

Go through NumPy documentation, and find a method which can be used to merge two numpy arrays as follows:

```
a = np.array([[10, 30, 15], [20, 10, 5]])
b = np.array([[45, 35, 20]])

merged_a_b = array([[10, 30, 15],
                    [20, 10, 5],
                    [45, 35, 20]])
```

Use that method and print the merged array.

## Answer 1

Example Output:

```
array([[10, 30, 15],
       [20, 10,  5],
       [45, 35, 20]])
```

# Question 2

Use a numpy method to duplicate contents of an array across rows and columns as follows:



```
a = np.array([[-2, -10],[5, -4]])

duplicated_rows_cols_a = array([[ -2,  -2,  -2, -10, -10, -10],
                                [  5,   5,   5,  -4,  -4,  -4]])

```



## Answer 2

Example Output:

```
array([[ -2,  -2,  -2, -10, -10, -10],
       [  5,   5,   5,  -4,  -4,  -4]])
```

# Question 3

Convert the array of size `(3, 2, 2)`



```
a = [
      [
        [10, 30, 15],
        [20, 10,  5]
      ],
      [
        [2, 6, 4],
        [9, 3,  0]
      ],
      [
        [-4, -8, -8],
        [-2, -9, -3]
      ]
    ]
```

into an array of size `(2, 3, 3)` by swapping the dimensions:



```
converted_a = [
                [
                  [10 30 15],
                  [ 2  6  4],
                  [-4 -8 -8]
                ],
                [
                  [20 10  5],
                  [ 9  3  0],
                  [-2 -9 -3]
                ]
              ]
```



## Answer 3

Example Output:

```
Shape of a: (3, 2, 3)

Shape of b: (2, 3, 3)
[[[10 30 15]
  [ 2  6  4]
  [-4 -8 -8]]

 [[20 10  5]
  [ 9  3  0]
  [-2 -9 -3]]]
```

# Data information and conversion

In [ ]:
print("Shape of 1 dimensional array: ",a.shape) # Array dimensions
print('-'*100)

print("Length of 1 dimensional array: ",len(a)) # Length of array
print('-'*100)

print("Number of array dimensions: ",b.ndim) # Number of array dimensions
print('-'*100)

print("Number of elements in array: ",c.size) # Number of array elements
print('-'*100)

print("Datatype of array: ",b.dtype)  # Data type of array elements
print('-'*100)

print("Name of array datatype: ",b.dtype.name)  # Name of data type
print('-'*100)

print("Converting float to int:\n",b.astype(int)) # Convert an array to a different type

# Mathematics

## Arithmetic operations

In [ ]:
# All basic operations on arrays can be done with a function and with operators as with scalars
print("Operator subtraction:\n", a - b)
print('-'*100)

print("Function subtraction:\n", np.subtract(a,b) )
print('-'*100)

print("Operator addition:\n", b + a)
print('-'*100)

print("Function addition:\n", np.add(b,a))
print('-'*100)

print('Take expontential:')
print(np.exp(b))
print('-'*100)

print('Take square root:')
print(np.sqrt(b))
print('-'*100)

print('Take sine:')
print(np.sin(a))
print('-'*100)

print('Take cosine:')
print(np.cos(b))
print('-'*100)

print('Take logarithm:')
print(np.log(a))

## Comparison

In [ ]:
print('Element-wise equality comparison')
print(a == b)
print('-'*100)

print('Element-wise inequality comparison')
print(a < b)

## Aggregate

In [ ]:
print('Take sum of all the elements of a')
print(a.sum())
print('-'*100)

print('Take minimum out of all the elements of a')
print(a.min())

# Subsetting, Slicing, Indexing

## Subsetting

In [ ]:
print('Element at the 2nd index')
print(a[2])
print('-'*100)

print('Element at 1st indexed row and 2nd indexed column')
print(b[1, 2])

## Slicing

In [ ]:
print('Elements from 0th to 1st index')
print(a[0:2])
print('-'*100)
print('')

print('Elements at 0th and 1st row and 1st column')
print(b[0:2, 1])
print('-'*100)
print('')

print('All elements at row 0')
print(b[:1])
print('-'*100)
print('')

print('Reversing the array')
print(a[::-1])

## Indexing

In [ ]:
print('Show all elements which are less than 2 in the array')
print(a[a < 2])

# Matrices

## Matrix Multiplciation:

Matrix multiplication is a fundamental operation in linear algebra and is used in a wide range of applications, including image processing, machine learning, and optimization. In NumPy, matrix multiplication can be performed using the dot function, which takes two arrays as input and returns their dot product.

In [ ]:
# Create two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Compute the dot product
C = np.dot(A, B)

print(C)

## Matrix Inverse
Matrix inversion is the process of finding the inverse of a matrix, which is a matrix that, when multiplied by the original matrix, produces the identity matrix. In NumPy, matrix inversion can be performed using the inv function, which takes a matrix as input and returns its inverse.



In [ ]:
# Create a matrix
A = np.array([[1, 2], [3, 4]])

# Compute the inverse
A_inv = np.linalg.inv(A)

print(A_inv)

## Matrix Determinant
The determinant of a matrix is a scalar value that can be used to determine certain properties of the matrix, such as whether it is invertible. In NumPy, matrix determinants can be computed using the det function, which takes a matrix as input and returns its determinant.

In [ ]:
# Create a matrix
A = np.array([[1, 2], [3, 4]])

# Compute the determinant
det_A = np.linalg.det(A)

print(det_A)

# Question 4

Multiply `[1, -1, 0]` with the **first** and the **third rows** of the given matrix `mat` row-wise, without using any loops.

The second row of `multiplied_mat` should remain the same as second row of `mat`.

## Answer 4

Example Output:

```
[[ 10 -20   0]
 [ 30  20  10]
 [ 30 -10   0]]
```

# Question 5

Look up NumPy documentation and find a method which can be used to calculate the **rank** of a matrix.

The **rank** of the matrix is the number of linearly independent column vectors in the matrix or the maximum number of linearly row vectors in the matrix.

In other words, the rank is how many of the rows are "unique": not made of other rows.

Print the rank of each of the following matricies.

In [ ]:
matrix1 = np.array([[1, 2, 3], [2, 4, 6]])

matrix2 = np.array([[1, 2, 3], [2, -4, 6]])

## Answer 5

Example Output:
```
1
2
```

References:

https://res.cloudinary.com/dyd911kmh/image/upload/v1676302459/Marketing/Blog/Numpy_Cheat_Sheet.pdf

### When you are ready to submit, upload this Notebook to your Github repository. (Check the guide to Github Classrooms to see how this works.)